services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - TZ=Europe/Warsaw
      - WEBPASSWORD=${WEBPASSWORD}
      - WEBTHEME=default-dark
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - /volume3/docker/pihole/etc:/etc/pihole:rw
      - /volume3/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
    restart: unless-stopped
    network_mode: host
